"""add_lead_source_and_quotation_status

Revision ID: 48376a972a42
Revises: e015035966b8
Create Date: 2026-06-18 02:41:56.879702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48376a972a42'
down_revision = 'e015035966b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=False, server_default='Website'))

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='pending'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('source')
    # ### end Alembic commands ###

