"""change project progress to integer

Revision ID: ba32962616da
Revises: a9a351f8aef9
Create Date: 2026-06-14 20:49:35.094070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba32962616da'
down_revision = 'a9a351f8aef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('progress_percentage',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('progress_percentage',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
