import os
import uuid
from flask import current_app
from app.models import db, File
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

def seed_files(customer_profile_id):
    """Seeds customer uploaded file record metadata and creates the physical file on disk.
    
    Args:
        customer_profile_id (str): The Customer profile UUID.
    """
    file_id = "6e6f0334-e0dd-47e6-a896-185e04f68b42"
    filename = "Worli_Apartment_Floorplan.pdf"
    file_url = "/static/uploads/worli_flat_402.pdf"
    
    customer_file = File(
        id=file_id,
        customer_id=customer_profile_id,
        filename=filename,
        file_url=file_url,
        file_type="pdf"
    )
    db.session.add(customer_file)
    db.session.flush()

    # Generate physical file in uploads folder
    upload_folder = os.path.join(current_app.root_path, 'static', 'uploads')
    os.makedirs(upload_folder, exist_ok=True)
    
    filepath = os.path.join(upload_folder, "worli_flat_402.pdf")
    if not os.path.exists(filepath):
        doc = SimpleDocTemplate(filepath, pagesize=letter)
        styles = getSampleStyleSheet()
        story = [
            Paragraph("Worli Apartment Floorplan", styles['Title']),
            Spacer(1, 20),
            Paragraph("This is the design floorplan layout for Flat 402 in the Worli Apartment project.", styles['Normal']),
            Spacer(1, 10),
            Paragraph("Seeded file automatically generated by the database setup scripts.", styles['Normal']),
            Spacer(1, 20),
            Paragraph("Crescent Chique Designs © 2026", styles['Normal'])
        ]
        doc.build(story)
        print(f"Generated seeded physical file: {filepath}")

